---
  - name: install erlang
    yum: 
      name: "https://github.com/rabbitmq/erlang-rpm/releases/download/{{ erlang_version }}/{{ erlang_release }}.rpm"
      state: present

  - name: install rabbitmq
    yum:
      name: "https://github.com/rabbitmq/rabbitmq-server/releases/download/{{ rabbitmq_version }}/{{ rabbitmq_release }}.rpm"
      state: present

  - name: rabbitmq config
    template:
      src: rabbitmq.conf.j2
      dest: /etc/rabbitmq/rabbitmq.conf
      owner: root
      group: root
      mode: 0644

  - name: check installed plugin
    stat:
      path: "/usr/lib//rabbitmq/lib/{{ rabbitmq-server }}/plugins/rabbitmq_delayed_message_exchange-3.8.9-0199d11c"
    register: delayed_message_exchange_installed
    
  - name: install rabbitmq delayed-message-exchange plugin
    unarchive:
      src: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.8.9/rabbitmq_delayed_message_exchange-3.8.9-0199d11c.ez
      dest: /usr/lib/rabbitmq/lib/{{ rabbitmq-server }}/plugins
      remote_src: yes
      owner: root
      group: root
      mode: 0644
    when: delayed_message_exchange_installed.stat.exists

  - name: enable rabbitmq management plugin
    command: /usr/sbin/rabbitmq-plugins enable rabbitmq_management

  - name: enable rabbitmq shovel plugin
    command: /usr/sbin/rabbitmq-plugins enable rabbitmq_shovel rabbitmq_shovel_management

  - name: enable rabbitmq delayed-message-exchange plugin
    command: /usr/sbin/rabbitmq-plugins enable rabbitmq_delayed_message_exchange

  - name: add user
    command: "/usr/sbin/rabbitmqctl add_user admin {{ password }}"

  - name: set_user_tags
    command: /usr/sbin/rabbitmqctl set_user_tags admin administrator

  - name: set_permissions
    command: /usr/sbin/rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
    notify: start rabbitmq