---

- hosts: all
  become: true
  tasks:

    - name: ensures /etc/jaeger dir
      file:
        path: /etc/jaeger
        state: directory
        owner: root
        group: root
        mode: 0766

    - name: create jaeger config file
      copy:
        src: jaeger-config.yaml
        dest: /etc/jaeger/jaeger-config.yaml
        owner: root
        group: root
        mode: 0644

    - name: check jaeger installed
      stat:
        path: /user/local/bin/jaeger
      register: jaeger_installed

    - name: install jaeger
      unarchive: 
        src: https://github.com/jaegertracing/jaeger/releases/download/v1.22.0/jaeger-1.22.0-linux-amd64.tar.gz
        dest: /root
        remote_src: yes
        mode: 0755
        owner: root
        group: root
      when: jaeger_installed.stat.exists

    - name: move jaeger dir
      command: mv /root/jaeger-1.22.0-linux-amd64 /user/local/bin/jaeger
      when: jaeger_installed.stat.exists

    - name: create jaeger service
      template:
        src: jaeger.service.j2
        dest: /etc/systemd/system/jaeger.service
        owner: root
        group: root
        mode: 0644

    - name: start jaeger
      become: true
      systemd:
        daemon_reload: true
        name: jaeger
        state: restarted

      