---

- hosts: all
  become: true
  tasks:

    - name: install jaeger
      unarchive: 
        src: https://github.com/jaegertracing/jaeger/releases/download/v1.22.0/jaeger-1.22.0-linux-amd64.tar.gz
        dest: /root
        remote_src: yes
        mode: 0755
        owner: root
        group: root

    - name: rename jaeger dir
      command: mv /root/jaeger-1.22.0-linux-amd64 /root/jaeger

      